# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YsawN0vryKvp7K1ouPUjzrK3cDirn91z
"""

#User Login Check
correct_user = "admin"
correct_pass = "1234"

entered_user = input("Enter username: ")
entered_pass = input("Enter password: ")

login_status = entered_user == correct_user and entered_pass == correct_pass

if login_status:
    print("Login Successful")
else:
    print("Invalid Credentials")

#Pass / Fail Analyze
scores = [45, 78, 90, 33, 60]

pass_students = sum(1 for mark in scores if mark >= 50)
fail_students = len(scores) - pass_students

print("Total:", len(scores))
print("Pass:", pass_students)
print("Fail:", fail_students)

#Simple Data Cleaner
names_list = [" Alice ", "bob", " CHARLIE "]

cleaned = list(map(lambda x: x.strip().lower(), names_list))

print(cleaned)

#Message Length Analyzer
msgs = ["Hi", "Welcome to the platform", "OK"]

for i in range(len(msgs)):
    print(msgs[i], "->", len(msgs[i]), "characters")

    if len(msgs[i]) > 10:
        print("Long message")

#Error Message Detector
log_data = ["INFO", "ERROR", "WARNING", "ERROR"]

errors = 0

for item in log_data:
    errors += 1 if item == "ERROR" else 0

print("Error Count:", errors)